services:

  apache:
    build: ./apache
    restart: on-failure
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      inner_network:
        aliases:
          - apache.domain
    depends_on:
      - webapp
      - broker

  webapp:
    image: zyndramzm/baca2-web-app:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - packages_volume:/usr/share/baca2_share/packages
    networks:
      inner_network:
        aliases:
          - webapp.domain
    environment:
      - PACKAGES_DIR=/usr/share/baca2_share/packages

      - HOST_IP=${WEBAPP_HOST_IP}
      - HOST_NAME=${WEBAPP_HOST_NAME}
      - AUTH_DOMAIN=${WEBAPP_AUTH_DOMAIN}
      - OIDC_RP_CLIENT_ID=${WEBAPP_OIDC_RP_CLIENT_ID}
      - USOS_GATEWAY=${WEBAPP_USOS_GATEWAY}
      - UPLOADS_DIR=${WEBAPP_UPLOADS_DIR}
      - TASK_DESCRIPTION_DIR=${WEBAPP_TASK_DESCRIPTION_DIR}
      - ATTACHMENTS_DIR=${WEBAPP_ATTACHMENTS_DIR}

      - SECRET_KEY=${WEBAPP_SECRET_KEY}
      - USOS_CONSUMER_KEY=${WEBAPP_USOS_CONSUMER_KEY}
      - USOS_CONSUMER_SECRET=${WEBAPP_USOS_CONSUMER_SECRET}

      - BACA2_DB_USER=${BACA2_DB_USER}
      - BACA2_DB_PASSWORD=${BACA2_DB_PASSWORD}
      - BACA2_DB_ROOT_USER=${BACA2_DB_ROOT_USER}
      - BACA2_DB_ROOT_PASSWORD=$[BACA2_DB_ROOT_PASSWORD}

      - EMAIL_USER=${WEBAPP_EMAIL_USER}
      - EMAIL_PASSWORD=${WEBAPP_EMAIL_PASSWORD}
      - OIDC_RP_CLIENT_SECRET=${WEBAPP_OIDC_RP_CLIENT_SECRET}

      - BACA_PASSWORD=${BACA_API_PASSWORD}
      - BROKER_PASSWORD=${BROKER_API_PASSWORD}

      - BACA2_DB_HOST=db.domain
      - BROKER_URL=http://broker.domain
    depends_on:
      - database

  broker:
    image: zyndramzm/baca2-broker:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - packages_volume:/usr/share/baca2_share/packages
    networks:
      inner_network:
        aliases:
          - broker.domain
    environment:
      - PACKAGES_DIR=/usr/share/baca2_share/packages
      - BACA_URL=http://webapp.domain/broker_api

      - SERVER_HOST=${BROKER_SERVER_HOST_IP}
      - SUBMITS_DIR=${SUBMITS_DIR}
      - SERVER_URL=${BROKER_SERVER_URL}  # public url for kolejka callback
      - ACTIVE_WAIT=${BROKER_ACTIVE_WAIT}

      - KOLEJKA_SERVER=${KOLEJKA_SERVER}
      - KOLEJKA_USERNAME=${KOLEJKA_USERNAME}
      - KOLEJKA_PASSWORD=${KOLEJKA_PASSWORD}

      - BACA_PASSWORD=${BACA_API_PASSWORD}
      - BROKER_PASSWORD=${BROKER_API_PASSWORD}

  database:
    image: postgres:latest
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - baca2_bd_volume:/var/lib/postgresql/data
    networks:
      inner_network:
        aliases:
          - db.domain
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}


volumes:
  packages_volume:
  baca2_bd_volume:

networks:
  inner_network:
